### ISSUE TITLE
defaultdict

### ISSUE THREAD

**Issue by kuzmichevdima** [kgrosul/random_text_generator#1]
https://github.com/kgrosul/reveiw/blob/b9ec8a301f9059d9d8a4629cd0d8c12e5cb5f499/train.py#L43-L46

чтобы избавиться от этого ифа, используй defaultdict(int)

https://github.com/kgrosul/reveiw/blob/b9ec8a301f9059d9d8a4629cd0d8c12e5cb5f499/train.py#L40-L41
аналогично defaultdict(dict)

**Comment by kgrosul** [comment]
@kuzmichevdima Вроде бы исправил
