### ISSUE TITLE
.keys(), .values()

### ISSUE THREAD

**Issue by kuzmichevdima** [kgrosul/random_text_generator#2]
https://github.com/kgrosul/reveiw/blob/b9ec8a301f9059d9d8a4629cd0d8c12e5cb5f499/train.py#L78-L80

сумма считается в 1 строчку с помощью sum и .values()

**Comment by kgrosul** [comment]
@kuzmichevdima Вроде бы исправил

**Comment by kuzmichevdima** [comment]
https://github.com/kgrosul/reveiw/blob/12e601b67b41f2aedaae6bd1bf5f30be7169762f/generate.py#L48-L52
здесь плохо то, что ты проходишься по всем ключам key и обращаешься к  model_dict[cur_words][key], хотя в реальности ты можешь просто найти сумму model_dict[cur_words].values().
зачем нужен tmp_words, я не понял. Почему бы не взять просто .keys()

**Comment by kgrosul** [comment]
@kuzmichevdima, исправил.
