### ISSUE TITLE
названия

### ISSUE THREAD

**Issue by kuzmichevdima** [kgrosul/random_text_generator#4]
https://github.com/kgrosul/reveiw/blob/12e601b67b41f2aedaae6bd1bf5f30be7169762f/train.py#L11-L14

key1, key2, tmp_,main_dict - ничего не говорят.

https://github.com/kgrosul/reveiw/blob/12e601b67b41f2aedaae6bd1bf5f30be7169762f/generate.py#L48-L54
tmp_words, tmp_p

**Comment by kgrosul** [comment]
@kuzmichevdima, исправил.
